version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.23.2
    steps:
      - checkout
      - run: make all
      - run: make cover-upload
workflows:
  version: 2
  workflow:
    jobs:
      - build
